In [5]:
import torch 
import torch.nn as nn
import numpy as np 
import matplotlib.pyplot as plt 
import time 

Pytorch is a python package with enables users to train state-of-the art machine learning/deep learning models.In order to efficiently use pytorch, one needs to have a firm underdtanding of the basic building blocks of pytorch: the torch.tensor object.In many ways , it's similar numpy array 

# Numpy vs. Torch

Numpy array's aand pytorch tensors can be created in the same way:

In [6]:
n = np.linspace(0,1,5)
t = torch.linspace(0,1,5)

They can be resized in similar ways

In [8]:
torch.arange(48)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [9]:
n = np.arange(48).reshape(3,4,4)
t = torch.arange(48).reshape(3,4,4)

# General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when
   1. they are equal, or
   2. one of them is 1
  Example: The following are compatible

  Shape 1: (1,6,4,1,7,2)

  Shape 2: (5,6,1,3,1,2)      

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [18]:
a = np.ones((6,5))
b = np.arange(5).reshape((1,5))
print(a,"\n",b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 [[0 1 2 3 4]]


In [16]:
a+b

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [19]:
a = torch.ones((6,5))
b = torch.arange(5).reshape((1,5))

The arrays/tensors don't need to have the same number of dimenions. If one of the arrays/tensors has less dimensions than the other

**Example**: Scaling each other the color channels of an image by a different amount:

     Image  (3d array): 256 x 256 x 3   
     Scale  (1d array):             3
     Result (3d array): 256 x 256 x 3
     
(3 values to each of these pixels red , blue and green so each pixels have three                                                 different values to scale for the colors )     

In [22]:
Scale = torch.tensor([0.5,1.5,1]) 
print(Scale)

tensor([0.5000, 1.5000, 1.0000])


all the pixels in my array i have red multiply by 1/2 , blue multiply ny 1.5 and keep green same . 
Now Scale is one dim array where Image is 3d array . Multiplication of these 2 array is happening like this 

if Image =
           
           [[[ 0.2, 1.2 , 0.4 ],
             [0.1, 0.19 , -0.7].
            [[ 0.9, 0.9 , 2.0 ]]]
Then    Image*Scale will be like [0.2 * 0.5 , 1.2* 1.5 , 0.4 * 1 ]    goes on .      
            

In [20]:
Image = torch.randn((256,256,3))
Scale = torch.tensor([0.5,1.5,1])

In [23]:
Result = Image*Scale

**Example**: One has an array of **2 images** and wants to scale the color channels of each image by a slightly different amount:

    Images  (4d array): 2 x 256 x 256 x 3
    Scales  (4d array): 2 x 1 x 1 x 3
    Results  (4d array): 2 x 256 x 256 x 3

we have 2 different pictures so hence 2 is there in first in Images whcih is called batch dimension in pytorch 

In [27]:
Images = torch.randn((2,256,256,3))
Scales = torch.tensor([0.5,1.5,1,1.5,1,0.5]).reshape((2,1,1,3)) ## reshape is very important here 

In [28]:
results = Images * Scales

# Operations Across Dimensions

This is so fundamental for pytorch. Obviously simple operations can be done one 1 dimensional tensors:

In [29]:
t = torch.tensor([0.5,1,3,4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(2.1250), tensor(1.6520), tensor(4.), tensor(0.5000))

But suppose we have a 2d tensor, for example, and want to compute the mean value of each columns:

* Note: taking the mean of each column means taking the mean across the rows (which are the first dimension)

In [32]:
t = torch.arange(20, dtype=float).reshape(5,4)
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=torch.float64)

We want to mean across the row to get the mean each col and here we can see that 8 will be mean of 1st col and 9 will be mean of 2nd col so on .

In [31]:
t = torch.arange(20, dtype=float).reshape(5,4)
torch.mean(t, axis=0)

tensor([ 8.,  9., 10., 11.], dtype=torch.float64)

This can be done for higher dimensionality arrays as well

In [33]:
t = torch.randn(5,256,256,3) ##5 images

Take the mean across the batch (size 5)


In [35]:
torch.mean(t,axis=0) ## Operation across the first axis here 

tensor([[[-2.7482e-01,  3.5627e-01,  2.0569e-01],
         [ 1.5947e-01, -1.8948e-01, -1.7222e-01],
         [-5.5312e-02, -1.4366e-01,  1.0664e-01],
         ...,
         [-9.6756e-02,  6.2063e-01,  1.8628e-01],
         [-1.3244e-01,  1.3641e-01, -3.8420e-01],
         [-2.1160e-01, -4.8154e-01,  1.5751e-01]],

        [[ 3.8579e-01,  4.9652e-01, -1.0070e-01],
         [-6.4069e-01,  7.5703e-01,  2.4229e-01],
         [-5.6776e-01, -6.6937e-01, -2.8263e-01],
         ...,
         [-5.2531e-01,  3.9014e-01,  3.6667e-01],
         [ 6.6242e-01, -2.9571e-02, -3.8872e-01],
         [-5.6407e-01,  5.9965e-01, -5.0289e-01]],

        [[-2.9267e-01, -7.8050e-02,  4.3210e-01],
         [ 4.9271e-01,  3.4681e-01, -3.8555e-01],
         [ 3.9004e-01, -4.3060e-02,  2.8223e-02],
         ...,
         [-2.3729e-01, -2.5815e-01, -7.9041e-01],
         [-1.2855e-02,  3.3961e-01, -1.9748e-01],
         [-6.6381e-01,  3.2402e-01,  8.7232e-01]],

        ...,

        [[-6.8224e-02, -9.0065e-01, -2

Take the mean across the color channels: 
want to average of the red blue and green power this might give a measure of brightness of each pixels that can convert to gray scale . 

In [37]:
torch.mean(t,axis=-1) ## Here we do the operation in last axis  (mean value of red , blue , green )

tensor([[[ 1.4106e+00, -2.7615e-01,  8.5342e-02,  ...,  7.2892e-02,
          -2.8161e-01,  2.6944e-01],
         [-3.5202e-01,  3.8313e-02, -6.5711e-01,  ..., -1.3036e-02,
           9.9509e-02, -2.8339e-01],
         [ 4.1021e-01,  3.5506e-01,  1.3502e-01,  ..., -5.5194e-01,
           5.0868e-01, -1.8840e-01],
         ...,
         [-1.6149e-01,  4.8096e-01, -4.3422e-01,  ...,  2.6981e-01,
           8.2800e-01,  7.1447e-01],
         [ 4.9447e-01, -9.8311e-02,  7.2643e-01,  ...,  2.5160e-01,
           2.0414e-01, -1.7318e-01],
         [ 9.9739e-01, -1.7489e-01, -6.6753e-01,  ...,  1.0314e+00,
           2.6161e-02,  1.2152e+00]],

        [[-2.4848e-01,  1.5002e-01, -5.2520e-01,  ...,  2.3190e-01,
          -4.1808e-01, -5.0253e-02],
         [ 7.8123e-01, -2.6072e-01,  1.5602e-02,  ...,  4.1701e-01,
          -5.3841e-01,  1.9789e-01],
         [ 1.7592e-01, -5.1292e-01,  1.9638e-01,  ..., -4.0130e-01,
          -1.0494e+00,  4.3987e-01],
         ...,
         [-9.2025e-01,  1

Take only the maximum color channel values (and get the corresponding indices):

* This is done all the time in image segmentation models (i.e. take an image, decide which pixels correspond to, say, a car)

In [38]:
values, indices = torch.max(t,axis=-1)

In [41]:
indices ## it gives the what specific color is maximum in that location 

tensor([[[1, 0, 2,  ..., 2, 0, 1],
         [0, 2, 0,  ..., 2, 2, 2],
         [2, 1, 0,  ..., 1, 2, 1],
         ...,
         [1, 1, 2,  ..., 1, 1, 2],
         [1, 2, 2,  ..., 0, 1, 0],
         [1, 2, 2,  ..., 0, 0, 0]],

        [[1, 1, 2,  ..., 2, 2, 0],
         [1, 1, 1,  ..., 0, 0, 1],
         [2, 1, 2,  ..., 1, 1, 2],
         ...,
         [0, 0, 1,  ..., 2, 0, 2],
         [0, 2, 0,  ..., 1, 2, 2],
         [0, 2, 0,  ..., 2, 2, 2]],

        [[2, 0, 0,  ..., 1, 1, 1],
         [0, 1, 2,  ..., 1, 1, 1],
         [0, 1, 0,  ..., 1, 0, 1],
         ...,
         [2, 0, 0,  ..., 2, 1, 1],
         [1, 1, 1,  ..., 2, 2, 0],
         [1, 0, 1,  ..., 0, 1, 1]],

        [[1, 1, 2,  ..., 1, 1, 0],
         [2, 1, 1,  ..., 2, 0, 1],
         [1, 0, 1,  ..., 0, 1, 2],
         ...,
         [2, 1, 1,  ..., 1, 2, 0],
         [0, 0, 1,  ..., 1, 2, 1],
         [0, 0, 0,  ..., 1, 0, 2]],

        [[1, 2, 0,  ..., 1, 1, 2],
         [1, 1, 0,  ..., 2, 2, 1],
         [1, 0, 2,  ..., 0

# So Where Do Pytorch and Numpy Differ?

**Pytorch** starts to really differ from **numpy** in terms of automatically computing gradients of operations

$$y = \sum_ix_i^3$$

has a gradient 

$$\frac{\partial y}{\partial x_i} = 3x_i^2$$

In [46]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)

In [47]:
x = torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)
y = x.pow(3).sum()
y

tensor(917., grad_fn=<SumBackward0>)

Compute the gradient:

In [48]:
y.backward() #compute the gradient
x.grad #print the gradient (everything that has happened to x) (everything stored in x !!)

tensor([[ 75., 192.],
        [ 48., 108.]])

Double check using the analytical formula:

In [49]:
3*x**2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)

The automatic computation of gradients is the backbone of training deep learning models. Unlike in the example above, most gradient computations don't have an analytical formula, so the automatic computation of gradients is essential. In general, if one has

$$y = f(\overrightarrow{x})$$

Then pytorch can compute $\partial y/\partial x_i$ For each of element of the vector $\vec{x}$ In the context of machine learning,   contains all the weights (also known as parameters) of the neural network and  is the y **Loss Function** of the neural network.

# Additional Benefits

In addition, any sort of large matrix multiplication problem is faster with torch tensors than it is with numpy arrays, especially if you're running on a GPU

Using torch: (with a CPU. With GPU, this is much much faster (40 times))

In [50]:
A = torch.randn((1000,1000))
B = torch.randn((1000,1000))

In [51]:
t1 = time.perf_counter()
torch.matmul(A,B)
t2 = time.perf_counter()
print(t2-t1)

0.034500700001444784


Using numpy:

In [52]:
A = np.random.randn(int(1e6)).reshape((1000,1000))
B = np.random.randn(int(1e6)).reshape((1000,1000))

In [53]:
t1 = time.perf_counter()
A@B
t2 = time.perf_counter()
print(t2-t1)

0.11953910000011092
